### ISSUE TITLE
Master branch won't build post - 7c9b034

### ISSUE THREAD

**Issue by loceee** [jason-tratta/ProgressScreen#4]
![screen shot 2016-08-02 at 1 23 57 pm](https://cloud.githubusercontent.com/assets/6110941/17316176/1a579198-58b5-11e6-9f1d-1d1e622438a3.png)
I can't get build master post this commit https://github.com/jason-tratta/ProgressScreen/commit/7c9b034cbae495717c8326fb2221ebba4d029062

It fails with attached errors. Commit https://github.com/jason-tratta/ProgressScreen/commit/c5232777cc1c3c6fd889bcafa02f0804b47e61a3 builds fine!

Thanks for a cool app!

**Comment by jason-tratta** [comment]
I think you need to update to the latest version of Xcode, the error you seeing there is likely due to the new Swift 3 syntax.

**Comment by loceee** [comment]
Thanks man. You are 100% correct. Updated and it builds fine. Sorry !
